In [2]:
from MakeDataset import X_train,X_test,y_test,y_train
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

Training data shape:  (126, 500, 3)
Testing data shape:  (54, 500, 3)


In [3]:


print(X_train)
print(X_train.shape)

[[[ 0.808328   -0.611463   -0.174325  ]
  [ 0.8607248  -0.6292507  -0.2072235 ]
  [ 0.9234049  -0.6139165  -0.1697608 ]
  ...
  [ 1.243735   -0.813674   -0.08746629]
  [ 1.310316   -0.9866524  -0.1899156 ]
  [ 1.288937   -0.862547   -0.2011721 ]]

 [[ 0.1477247   0.8507512   0.5077734 ]
  [ 0.1461681   0.8474511   0.505222  ]
  [ 0.1448022   0.8482049   0.4994953 ]
  ...
  [ 0.1462152   0.8456498   0.5124658 ]
  [ 0.1423566   0.8459015   0.5107313 ]
  [ 0.1426939   0.8446308   0.5075358 ]]

 [[ 1.025523   -0.04926786  0.05208086]
  [ 1.024647   -0.05038679  0.05060927]
  [ 1.024841   -0.05028516  0.05457738]
  ...
  [ 1.021391   -0.09425633 -0.02702328]
  [ 1.023305   -0.09057553 -0.02542393]
  [ 1.020692   -0.09100618 -0.0220361 ]]

 ...

 [[ 0.06220856  0.6501921   0.7592214 ]
  [ 0.06956316  0.6425034   0.7632123 ]
  [ 0.07507962  0.6391476   0.766747  ]
  ...
  [ 0.08382917  0.6482952   0.7786019 ]
  [ 0.08575425  0.6472358   0.7767607 ]
  [ 0.0842131   0.6468174   0.7731877 ]]

 [

In [10]:
print(X_test)
print(X_test.shape)

[[[ 0.7078369   0.0730811   0.02283208]
  [ 0.6624463   0.05144334 -0.00816114]
  [ 0.705374    0.1038413   0.05359853]
  ...
  [ 0.9046059  -0.08509045  0.2273911 ]
  [ 1.047739   -0.00506888  0.1905655 ]
  [ 1.148507   -0.04968361  0.1064891 ]]

 [[ 0.9812334   0.0079993  -0.1335057 ]
  [ 0.9352486   0.05657511 -0.1182152 ]
  [ 0.9452209   0.06996628 -0.114189  ]
  ...
  [ 0.8287504  -0.03664244 -0.2026902 ]
  [ 0.8803827  -0.05294378 -0.1765659 ]
  [ 0.8965613   0.01316956 -0.1347441 ]]

 [[ 0.879989   -0.1716172   0.2579813 ]
  [ 0.8589097  -0.1025834   0.2582785 ]
  [ 0.9049145  -0.09320882  0.2876563 ]
  ...
  [ 0.8051944  -0.2893083  -0.06420045]
  [ 0.8403078  -0.1393827  -0.1220374 ]
  [ 0.951038   -0.05591341 -0.1139738 ]]

 ...

 [[-0.338486   -0.5257631   0.7826314 ]
  [-0.3486269  -0.5197535   0.7867927 ]
  [-0.3473831  -0.5056994   0.7933079 ]
  ...
  [ 0.1286809   0.9977822  -0.1146345 ]
  [ 0.1283305   0.9902453  -0.1184711 ]
  [ 0.127832    0.992517   -0.1184475 ]]

 [

In [9]:
print(y_train)
print(y_train.shape)

[2 6 5 2 2 2 1 1 5 4 1 4 1 1 6 2 3 1 1 4 3 3 5 6 5 1 3 6 4 5 5 2 5 1 1 6 4
 3 3 3 3 4 6 3 4 1 2 2 6 5 5 3 6 6 4 3 4 2 4 5 5 5 5 4 6 6 4 5 3 4 3 1 4 4
 3 1 5 2 3 6 1 4 2 2 5 2 1 3 6 6 2 5 6 1 3 5 2 3 4 4 2 5 1 1 1 3 4 5 6 1 3
 6 5 4 2 2 6 2 6 6 3 1 4 6 2 2]
(126,)


In [8]:
print(y_test)
print(y_test.shape)


[3 1 2 5 5 1 1 5 3 2 6 5 6 5 6 1 6 5 2 5 4 3 2 2 1 4 6 4 1 2 6 2 4 4 3 6 6
 3 1 5 3 2 1 4 4 4 5 1 3 3 3 6 2 4]
(54,)


In [3]:
print(X_train[y_train==5])

[[[ 1.025523   -0.04926786  0.05208086]
  [ 1.024647   -0.05038679  0.05060927]
  [ 1.024841   -0.05028516  0.05457738]
  ...
  [ 1.021391   -0.09425633 -0.02702328]
  [ 1.023305   -0.09057553 -0.02542393]
  [ 1.020692   -0.09100618 -0.0220361 ]]

 [[ 1.023096   -0.1374412  -0.04878418]
  [ 1.025108   -0.1355485  -0.0457131 ]
  [ 1.025216   -0.131584   -0.04451384]
  ...
  [ 1.022193   -0.1285125  -0.06552104]
  [ 1.022327   -0.133623   -0.06736659]
  [ 1.022025   -0.1386613  -0.06576266]]

 [[ 1.013856   -0.08463204 -0.1833906 ]
  [ 1.018295   -0.08470217 -0.1755404 ]
  [ 1.017008   -0.08552211 -0.1765002 ]
  ...
  [ 1.009988   -0.09727326 -0.1556776 ]
  [ 1.009527   -0.1015205  -0.1545634 ]
  [ 1.012576   -0.1036466  -0.1521443 ]]

 ...

 [[ 1.011292   -0.1764318   0.1089055 ]
  [ 1.011791   -0.1765343   0.1074459 ]
  [ 1.012158   -0.1772783   0.1043515 ]
  ...
  [ 1.012946   -0.1634221   0.1327974 ]
  [ 1.014234   -0.1619069   0.1316265 ]
  [ 1.014367   -0.1627081   0.1317076 ]]

 [