<h1>TASK 4.2</h1>

Question 1

In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import os
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [30]:
import sys
sys.path.append('/Users/tanishqchaudhari/Desktop/Collected data/Collected Data 2')
from Make_collected_dataset import X,Y

In [39]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [2]:

# X_train_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/X_train_tsfel.csv')
# y_train_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/y_train_tsfel.csv')
X_collected_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/X_collected_tsfel.csv')
y_collected_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/y_collected_tsfel.csv')

In [ ]:
X_collected=pd.read_csv('')

In [ ]:
df = pd.DataFrame()
df_test = pd.DataFrame()
dict1 = {"LAYING":0,
"SITTING":1,
"STANDING":2,
"WALKING":3,
"WALKING_DOWNSTAIRS":4,
"WALKING_UPSTAIRS":5}

In [ ]:

base_path = "/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/Combined/Train"

# Initialize an empty DataFrame
df = pd.DataFrame()

for files in os.listdir(base_path):
    full_path = os.path.join(base_path, files)
    if os.path.isdir(full_path):  # Ensure `files` is a directory
        for dfs in os.listdir(full_path):
            dfs_full_path = os.path.join(full_path, dfs)
            if os.path.isfile(dfs_full_path):  # Ensure `dfs` is a file
                df1 = pd.read_csv(dfs_full_path)
                df1["Label"] = np.array([dict1[files]] * df1.shape[0])
                df = pd.concat([df, df1], axis=0)

# Now `df` contains the combined DataFrame

In [ ]:


base_path = "/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/Combined/Test"

# Initialize an empty DataFrame
df_test = pd.DataFrame()

for files in os.listdir(base_path):
    full_path = os.path.join(base_path, files)
    if os.path.isdir(full_path):  # Ensure `files` is a directory
        for dfs in os.listdir(full_path):
            dfs_full_path = os.path.join(full_path, dfs)
            if os.path.isfile(dfs_full_path):  # Ensure `dfs` is a file
                df1 = pd.read_csv(dfs_full_path)
                df1["Label"] = np.array([dict1[files]] * df1.shape[0])
                df_test = pd.concat([df_test, df1], axis=0)

# Now `df` contains the combined DataFrame


In [35]:
print(type(Y))

<class 'numpy.ndarray'>


In [32]:
X_flattened = X.reshape(24, -1)

In [41]:


X_collected=pd.DataFrame(X_flattened)
X_collected

0     1     2     3     4     5     6     7     8     9     ...  1490  \
0  -0.54  0.41 -2.97 -1.18 -0.67 -4.52 -2.21 -1.94 -3.91 -2.86  ...  3.18   
1  -0.01  0.03  0.02  0.01  0.02  0.01 -0.02 -0.01  0.02 -0.01  ... -0.01   
2   0.54 -0.52 -1.54  1.37 -1.35 -1.61  0.21 -1.96 -2.35 -1.43  ...  4.73   
3   0.14  0.08 -0.19  0.14  0.10 -0.11  0.19  0.13  0.03  0.24  ... -0.03   
4   3.46 -1.79 -1.64  2.95 -2.15 -1.93  0.21 -1.40 -2.09  0.00  ... -4.14   
5  -0.08  0.02  0.01 -0.07  0.02  0.01 -0.02  0.01  0.02 -0.00  ...  0.03   
6   2.36 -3.70  5.21  1.94 -1.85  4.70  1.96 -2.36  7.77  1.15  ... -3.93   
7  -0.04 -0.01 -0.03 -0.07 -0.00 -0.07 -0.07  0.02 -0.11 -0.06  ...  0.01   
8  -0.05  0.19  0.09 -0.09  0.21  0.08 -0.04  0.11  0.04 -0.06  ... -0.01   
9   0.00 -0.01  0.01 -0.01 -0.01  0.01  0.01  0.01 -0.00 -0.00  ... -3.64   
10  0.06  0.04 -0.01  0.06  0.02  0.01  0.04  0.03  0.01  0.03  ...  0.00   
11 -1.44  1.44 -1.00 -1.87  0.68 -0.77 -1.83 -0.92 -0.54 -1.85  ... -1.82   
12  0.01  0.00  0.04  0.03  0.01  0.02  0.07  0.01 -0.08 -0.01  ... -0.01   
13  0.51 -0.33 -2.98 -1.19 -0.22 -2.97 -4.02 -2.06 -2.42 -4.61  ... -3.64   
14 -0.01  0.02  0.01  0.01 -0.02 -0.04  0.03  0.00 -0.05  0.03  ... -0.01   
15  0.12 -0.07 -0.06  0.11 -0.03 -0.07  0.09  0.04 -0.09  0.05  ... -0.00   
16  0.01 -0.01 -0.06  0.03  0.09  0.00  0.02  0.10  0.05  0.05  ... -0.01   
17  0.92 -0.30 -1.04  0.60 -0.00 -1.92  1.02 -0.26 -2.52  1.03  ... -0.78   
18  0.12 -0.03 -0.02  0.11 -0.02 -0.06  0.07  0.02 -0.01  0.01  ...  0.03   
19  0.23 -0.24  0.06  0.55 -0.48 -0.84  0.83 -0.22 -1.60  0.57  ...  2.63   
20  0.92  0.14 -0.63  0.54  0.17 -1.27 -0.01  0.38 -1.46 -0.16  ... -1.83   
21  0.42 -0.64 -2.00  0.12 -0.70 -2.18  0.10 -0.44 -2.33  0.51  ... -4.21   
22  2.04 -0.86 -0.80  1.24 -0.81 -0.63  0.58 -0.37 -0.49  0.30  ...  2.28   
23  0.79  0.27 -0.61  0.56  0.58 -0.56 -0.18  0.66 -0.68 -1.02  ... -0.68   

    1491  1492  1493  1494  1495  1496  1497  1498  1499  
0   1.07 -3.17  4.60  0.59 -2.50  3.80  1.05 -1.77  5.68  
1   0.02 -0.00 -0.02  0.01  0.00 -0.01  0.01  0.00  0.00  
2  -0.80 -0.89  2.83  0.79 -1.38  2.23  2.04 -1.20  2.34  
3  -0.01  0.01 -0.03  0.01  0.02 -0.02  0.04 -0.06 -0.00  
4  -2.66  1.72 -3.57 -1.37  0.53 -1.88  0.04 -1.92  0.79  
5  -0.02  0.00  0.03 -0.03 -0.01  0.03 -0.02 -0.00  0.01  
6   0.30  0.51 -1.36 -0.65 -0.46  1.44 -1.84 -2.15  2.84  
7  -0.02  0.02 -0.00 -0.00  0.02 -0.00 -0.00  0.00 -0.00  
8   0.03  0.08 -0.02  0.01  0.11  0.01  0.01  0.00  0.03  
9   2.67  0.89 -2.64  3.11  0.39 -2.27  0.30 -2.20 -2.01  
10  0.03 -0.01 -0.08  0.06 -0.02 -0.11  0.05 -0.02 -0.09  
11  1.34 -1.39 -2.91  3.29 -2.71 -2.47  3.85 -3.50 -1.19  
12  0.05 -0.01 -0.03  0.02  0.01 -0.05  0.02  0.00 -0.03  
13  0.10 -0.34 -3.99 -1.05 -5.76 -1.55 -1.28 -9.37  2.79  
14 -0.09  0.01  0.04 -0.13  0.01  0.15 -0.03  0.08  0.15  
15  0.01 -0.00 -0.00 -0.23 -1.30  0.57 -0.54  0.69  0.04  
16 -0.02 -0.00  0.00 -0.03 -0.02 -0.01  0.04 -0.04  0.05  
17 -1.13  0.83  1.07  2.70  0.49  1.72  3.97 -0.57  0.67  
18  0.07  0.03 -0.03  0.03 -0.01 -0.01 -0.01 -0.02 -0.01  
19  0.49 -1.40  0.89  0.16 -0.74  0.70  0.21 -0.56  1.47  
20  2.42 -2.71 -0.78  2.81 -5.00 -0.11  0.74 -3.77 -1.21  
21  0.38 -0.75 -3.03 -0.62  0.60 -1.99 -2.17  1.35 -1.84  
22 -0.79  0.71  0.79 -0.08  0.97  0.69  0.85  0.87  1.38  
23  0.40  0.08 -0.29  1.25 -0.21  0.14  1.68 -0.03  0.32  

[24 rows x 1500 columns]

In [42]:
y_collected=pd.DataFrame(Y)
y_collected

0
0   1
1   6
2   1
3   6
4   1
5   6
6   1
7   6
8   5
9   4
10  5
11  3
12  5
13  3
14  5
15  4
16  4
17  3
18  4
19  3
20  2
21  2
22  2
23  2

In [37]:
dt = DecisionTreeClassifier(criterion="gini", random_state=42,
        splitter="best",
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        min_weight_fraction_leaf=0.0,
        max_features=None,
        max_leaf_nodes=None,
        min_impurity_decrease=0.0,
        class_weight=None,
        ccp_alpha=0.0,
        monotonic_cst=None)

In [38]:
dt.fit(X_df,Y_df)

DecisionTreeClassifier(random_state=42)

In [44]:
X_collected_train, X_collected_test, y_collected_train, y_collected_test = train_test_split(X_collected, y_collected, test_size=0.3, random_state=42)

In [45]:
dt.fit(X_collected_train, y_collected_train)

DecisionTreeClassifier(random_state=42)

In [46]:
predictions = dt.predict(X_collected_test)

In [47]:
accuracy = accuracy_score(predictions, y_collected_test)
print(f"Accuracy: {accuracy}")

Accuracy: 0.125


In [48]:
precision = precision_score(predictions, y_collected_test,average="weighted")
print(f"Precision: {precision}")

Precision: 0.5


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [49]:
recall = recall_score(predictions, y_collected_test,average="weighted")
print(f"Recall: {recall}")

Recall: 0.125


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [50]:


mat = confusion_matrix(predictions, y_collected_test)
print(f"Confusion Matrix:\n{mat}")


Confusion Matrix:
[[0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 2 1 1]]


In [9]:
X_collected_tsfel_train, X_collected_tsfel_test, y_collected_tsfel_train, y_collected_tsfel_test = train_test_split(X_collected_tsfel.iloc[1:,:], y_collected_tsfel, test_size=0.3, random_state=42)

In [10]:
dt.fit(X_collected_tsfel_train, y_collected_tsfel_train)

DecisionTreeClassifier(random_state=42)

In [11]:
predictions = dt.predict(X_collected_tsfel_test)

In [13]:
accuracy = accuracy_score(predictions, y_collected_tsfel_test)
print(f"Accuracy: {accuracy}")

Accuracy: 0.7142857142857143


In [14]:
precision = precision_score(predictions, y_collected_tsfel_test,average="weighted")
print(f"Precision: {precision}")

Precision: 0.7857142857142857


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [15]:
recall = recall_score(predictions, y_collected_tsfel_test,average="weighted")
print(f"Recall: {recall}")

Recall: 0.7142857142857143


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [16]:
from sklearn.metrics import confusion_matrix

mat = confusion_matrix(predictions, y_collected_tsfel_test)
print(f"Confusion Matrix:\n{mat}")


Confusion Matrix:
[[0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 2 0]
 [0 0 1 0 2]]


It can be clearly seen that that after featurization using tsfel the model performed substansially better