<h1>TASK 4.2</h1>

Question 1

In [76]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import os
from sklearn.tree import DecisionTreeClassifier

In [77]:

X_train_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/X_train_tsfel.csv')
y_train_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/y_train_tsfel.csv')
X_test_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/X_collected_tsfel.csv')
y_test_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/y_collected_tsfel.csv')

In [78]:
df = pd.DataFrame()
df_test = pd.DataFrame()
dict1 = {"LAYING":0,
"SITTING":1,
"STANDING":2,
"WALKING":3,
"WALKING_DOWNSTAIRS":4,
"WALKING_UPSTAIRS":5}

In [79]:

base_path = "/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/Combined/Train"

# Initialize an empty DataFrame
df = pd.DataFrame()

for files in os.listdir(base_path):
    full_path = os.path.join(base_path, files)
    if os.path.isdir(full_path):  # Ensure `files` is a directory
        for dfs in os.listdir(full_path):
            dfs_full_path = os.path.join(full_path, dfs)
            if os.path.isfile(dfs_full_path):  # Ensure `dfs` is a file
                df1 = pd.read_csv(dfs_full_path)
                df1["Label"] = np.array([dict1[files]] * df1.shape[0])
                df = pd.concat([df, df1], axis=0)

# Now `df` contains the combined DataFrame

In [80]:
df[df['Label']==1]

accx      accy      accz  Label
0     0.988581  0.196507  0.180045      1
1     0.985708  0.198905  0.192556      1
2     0.979526  0.204315  0.204461      1
3     0.980467  0.204519  0.204332      1
4     0.984234  0.204112  0.201085      1
...        ...       ...       ...    ...
3003  0.983336  0.147791  0.221924      1
3004  0.976038  0.141747  0.220276      1
3005  0.972944  0.137397  0.221315      1
3006  0.971183  0.135625  0.231532      1
3007  0.970699  0.137976  0.245045      1

[82304 rows x 4 columns]

In [81]:


base_path = "/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/Combined/Test"

# Initialize an empty DataFrame
df_test = pd.DataFrame()

for files in os.listdir(base_path):
    full_path = os.path.join(base_path, files)
    if os.path.isdir(full_path):  # Ensure `files` is a directory
        for dfs in os.listdir(full_path):
            dfs_full_path = os.path.join(full_path, dfs)
            if os.path.isfile(dfs_full_path):  # Ensure `dfs` is a file
                df1 = pd.read_csv(dfs_full_path)
                df1["Label"] = np.array([dict1[files]] * df1.shape[0])
                df_test = pd.concat([df_test, df1], axis=0)

# Now `df` contains the combined DataFrame


In [82]:
df_test[df_test['Label']==1]

accx      accy      accz  Label
0     0.951905  0.133459  0.324955      1
1     0.954166  0.140860  0.326493      1
2     0.958054  0.144883  0.328487      1
3     0.955355  0.155393  0.326331      1
4     0.950674  0.164610  0.326728      1
...        ...       ...       ...    ...
3259  1.017505  0.024498 -0.039603      1
3260  1.019046  0.025779 -0.049137      1
3261  1.028794  0.014717 -0.066147      1
3262  1.031831  0.015192 -0.069162      1
3263  1.027248  0.017098 -0.065781      1

[31424 rows x 4 columns]

In [83]:
dt = DecisionTreeClassifier(criterion="gini", random_state=42,
        splitter="best",
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        min_weight_fraction_leaf=0.0,
        max_features=None,
        max_leaf_nodes=None,
        min_impurity_decrease=0.0,
        class_weight=None,
        ccp_alpha=0.0,
        monotonic_cst=None)

In [84]:
dt.fit(X_train_tsfel[1:126], y_train_tsfel)

DecisionTreeClassifier(random_state=42)

In [85]:
predictions = dt.predict(X_test_tsfel[1:25])

In [86]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [87]:
accuracy = accuracy_score(predictions, y_test_tsfel)
print(f"Accuracy: {accuracy}")

Accuracy: 0.21739130434782608


In [88]:
precision = precision_score(predictions, y_test_tsfel,average="weighted")
print(f"Precision: {precision}")

Precision: 0.8369565217391305


In [89]:
recall = recall_score(predictions, y_test_tsfel,average="weighted")
print(f"Recall: {recall}")

Recall: 0.21739130434782608


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [90]:
from sklearn.metrics import confusion_matrix

mat = confusion_matrix(predictions, y_test_tsfel)
print(f"Confusion Matrix:\n{mat}")


Confusion Matrix:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [2 1 0 0 0 0]
 [2 3 3 3 4 4]]


Question 2


From the above observations we can infer that the decision tree doesnt perform well when the depth of the tree is less than 3 and has a drastic shoot in accuracy after a depth of 3. We also observe that the model performs better with more features as compared to the raw accelerometer data where there are only 3 features.