<h1>TASK 4.2</h1>

Question 1

In [88]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import os
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [62]:
import sys
sys.path.append('/Users/tanishqchaudhari/Desktop/Collected data/Collected Data 2')
from Make_collected_dataset import X,Y

In [63]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [64]:

# X_train_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/X_train_tsfel.csv')
# y_train_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/y_train_tsfel.csv')
X_collected_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/X_collected_tsfel.csv')
y_collected_tsfel=pd.read_csv('/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/y_collected_tsfel.csv')

In [65]:
df = pd.DataFrame()
df_test = pd.DataFrame()
dict1 = {"LAYING":0,
"SITTING":1,
"STANDING":2,
"WALKING":3,
"WALKING_DOWNSTAIRS":4,
"WALKING_UPSTAIRS":5}

In [66]:

base_path = "/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/Combined/Train"

# Initialize an empty DataFrame
df = pd.DataFrame()

for files in os.listdir(base_path):
    full_path = os.path.join(base_path, files)
    if os.path.isdir(full_path):  # Ensure `files` is a directory
        for dfs in os.listdir(full_path):
            dfs_full_path = os.path.join(full_path, dfs)
            if os.path.isfile(dfs_full_path):  # Ensure `dfs` is a file
                df1 = pd.read_csv(dfs_full_path)
                df1["Label"] = np.array([dict1[files]] * df1.shape[0])
                df = pd.concat([df, df1], axis=0)

# Now `df` contains the combined DataFrame

In [67]:


base_path = "/Users/tanishqchaudhari/Desktop/Cloned Git Repos/ML_Assignment_1/human+activity+recognition+using+smartphones/UCI HAR Dataset/Combined/Test"

# Initialize an empty DataFrame
df_test = pd.DataFrame()

for files in os.listdir(base_path):
    full_path = os.path.join(base_path, files)
    if os.path.isdir(full_path):  # Ensure `files` is a directory
        for dfs in os.listdir(full_path):
            dfs_full_path = os.path.join(full_path, dfs)
            if os.path.isfile(dfs_full_path):  # Ensure `dfs` is a file
                df1 = pd.read_csv(dfs_full_path)
                df1["Label"] = np.array([dict1[files]] * df1.shape[0])
                df_test = pd.concat([df_test, df1], axis=0)

# Now `df` contains the combined DataFrame


In [68]:
print(type(Y))

<class 'numpy.ndarray'>


In [69]:
X_flattened = X.reshape(24, -1)

In [70]:


X_collected=pd.DataFrame(X_flattened)
X_collected

0     1     2     3     4     5     6     7     8     9     ...  1490  \
0  -0.54  0.41 -2.97 -1.18 -0.67 -4.52 -2.21 -1.94 -3.91 -2.86  ...  3.18   
1  -0.01  0.03  0.02  0.01  0.02  0.01 -0.02 -0.01  0.02 -0.01  ... -0.01   
2   0.54 -0.52 -1.54  1.37 -1.35 -1.61  0.21 -1.96 -2.35 -1.43  ...  4.73   
3   0.14  0.08 -0.19  0.14  0.10 -0.11  0.19  0.13  0.03  0.24  ... -0.03   
4   3.46 -1.79 -1.64  2.95 -2.15 -1.93  0.21 -1.40 -2.09  0.00  ... -4.14   
5  -0.08  0.02  0.01 -0.07  0.02  0.01 -0.02  0.01  0.02 -0.00  ...  0.03   
6   2.36 -3.70  5.21  1.94 -1.85  4.70  1.96 -2.36  7.77  1.15  ... -3.93   
7  -0.04 -0.01 -0.03 -0.07 -0.00 -0.07 -0.07  0.02 -0.11 -0.06  ...  0.01   
8  -0.05  0.19  0.09 -0.09  0.21  0.08 -0.04  0.11  0.04 -0.06  ... -0.01   
9   0.00 -0.01  0.01 -0.01 -0.01  0.01  0.01  0.01 -0.00 -0.00  ... -3.64   
10  0.06  0.04 -0.01  0.06  0.02  0.01  0.04  0.03  0.01  0.03  ...  0.00   
11 -1.44  1.44 -1.00 -1.87  0.68 -0.77 -1.83 -0.92 -0.54 -1.85  ... -1.82   
12  0.01  0.00  0.04  0.03  0.01  0.02  0.07  0.01 -0.08 -0.01  ... -0.01   
13  0.51 -0.33 -2.98 -1.19 -0.22 -2.97 -4.02 -2.06 -2.42 -4.61  ... -3.64   
14 -0.01  0.02  0.01  0.01 -0.02 -0.04  0.03  0.00 -0.05  0.03  ... -0.01   
15  0.12 -0.07 -0.06  0.11 -0.03 -0.07  0.09  0.04 -0.09  0.05  ... -0.00   
16  0.01 -0.01 -0.06  0.03  0.09  0.00  0.02  0.10  0.05  0.05  ... -0.01   
17  0.92 -0.30 -1.04  0.60 -0.00 -1.92  1.02 -0.26 -2.52  1.03  ... -0.78   
18  0.12 -0.03 -0.02  0.11 -0.02 -0.06  0.07  0.02 -0.01  0.01  ...  0.03   
19  0.23 -0.24  0.06  0.55 -0.48 -0.84  0.83 -0.22 -1.60  0.57  ...  2.63   
20  0.92  0.14 -0.63  0.54  0.17 -1.27 -0.01  0.38 -1.46 -0.16  ... -1.83   
21  0.42 -0.64 -2.00  0.12 -0.70 -2.18  0.10 -0.44 -2.33  0.51  ... -4.21   
22  2.04 -0.86 -0.80  1.24 -0.81 -0.63  0.58 -0.37 -0.49  0.30  ...  2.28   
23  0.79  0.27 -0.61  0.56  0.58 -0.56 -0.18  0.66 -0.68 -1.02  ... -0.68   

    1491  1492  1493  1494  1495  1496  1497  1498  1499  
0   1.07 -3.17  4.60  0.59 -2.50  3.80  1.05 -1.77  5.68  
1   0.02 -0.00 -0.02  0.01  0.00 -0.01  0.01  0.00  0.00  
2  -0.80 -0.89  2.83  0.79 -1.38  2.23  2.04 -1.20  2.34  
3  -0.01  0.01 -0.03  0.01  0.02 -0.02  0.04 -0.06 -0.00  
4  -2.66  1.72 -3.57 -1.37  0.53 -1.88  0.04 -1.92  0.79  
5  -0.02  0.00  0.03 -0.03 -0.01  0.03 -0.02 -0.00  0.01  
6   0.30  0.51 -1.36 -0.65 -0.46  1.44 -1.84 -2.15  2.84  
7  -0.02  0.02 -0.00 -0.00  0.02 -0.00 -0.00  0.00 -0.00  
8   0.03  0.08 -0.02  0.01  0.11  0.01  0.01  0.00  0.03  
9   2.67  0.89 -2.64  3.11  0.39 -2.27  0.30 -2.20 -2.01  
10  0.03 -0.01 -0.08  0.06 -0.02 -0.11  0.05 -0.02 -0.09  
11  1.34 -1.39 -2.91  3.29 -2.71 -2.47  3.85 -3.50 -1.19  
12  0.05 -0.01 -0.03  0.02  0.01 -0.05  0.02  0.00 -0.03  
13  0.10 -0.34 -3.99 -1.05 -5.76 -1.55 -1.28 -9.37  2.79  
14 -0.09  0.01  0.04 -0.13  0.01  0.15 -0.03  0.08  0.15  
15  0.01 -0.00 -0.00 -0.23 -1.30  0.57 -0.54  0.69  0.04  
16 -0.02 -0.00  0.00 -0.03 -0.02 -0.01  0.04 -0.04  0.05  
17 -1.13  0.83  1.07  2.70  0.49  1.72  3.97 -0.57  0.67  
18  0.07  0.03 -0.03  0.03 -0.01 -0.01 -0.01 -0.02 -0.01  
19  0.49 -1.40  0.89  0.16 -0.74  0.70  0.21 -0.56  1.47  
20  2.42 -2.71 -0.78  2.81 -5.00 -0.11  0.74 -3.77 -1.21  
21  0.38 -0.75 -3.03 -0.62  0.60 -1.99 -2.17  1.35 -1.84  
22 -0.79  0.71  0.79 -0.08  0.97  0.69  0.85  0.87  1.38  
23  0.40  0.08 -0.29  1.25 -0.21  0.14  1.68 -0.03  0.32  

[24 rows x 1500 columns]

In [71]:
y_collected=pd.DataFrame(Y)
y_collected

0
0   1
1   6
2   1
3   6
4   1
5   6
6   1
7   6
8   5
9   4
10  5
11  3
12  5
13  3
14  5
15  4
16  4
17  3
18  4
19  3
20  2
21  2
22  2
23  2

In [98]:
s1 = StandardScaler()
s2= StandardScaler()


X_collected_standardized = pd.DataFrame(s1.fit_transform(X_collected), columns=X_collected.columns)

X_collected_standardized_tsfel = pd.DataFrame(s2.fit_transform(X_collected_tsfel), columns=X_collected_tsfel.columns)

In [92]:
X_collected_standardized

0         1         2         3         4         5         6     \
0  -1.005295  0.725812 -1.711654 -1.485763 -0.597261 -2.456012 -1.862026   
1  -0.459760  0.304462  0.296985 -0.245383  0.425556  0.391569  0.092599   
2   0.106362 -0.305386 -0.751000  1.172194 -1.605254 -0.626772  0.297879   
3  -0.305363  0.359903  0.155910 -0.109880  0.544143  0.316136  0.280029   
4   3.111955 -1.713581 -0.818179  2.819085 -2.791128 -0.827925  0.297879   
5  -0.531811  0.293374  0.290267 -0.328770  0.425556  0.391569  0.092599   
6   1.979711 -3.831418  3.783552  1.766325 -2.346425  3.339726  1.859794   
7  -0.490639  0.260110  0.263396 -0.328770  0.395909  0.341280  0.047973   
8  -0.500932  0.481873  0.344010 -0.349617  0.707201  0.435571  0.074749   
9  -0.449466  0.260110  0.290267 -0.266230  0.381086  0.391569  0.119375   
10 -0.387708  0.315550  0.276832 -0.193266  0.425556  0.391569  0.146151   
11 -1.931676  1.867891 -0.388236 -2.204975  1.403902 -0.098743 -1.522867   
12 -0.439173  0.271198  0.310421 -0.224537  0.410732  0.397855  0.172926   
13  0.075483 -0.094711 -1.718371 -1.496187  0.069794 -1.481675 -3.477492   
14 -0.459760  0.293374  0.290267 -0.245383  0.366262  0.360138  0.137225   
15 -0.325949  0.193581  0.243242 -0.141150  0.351439  0.341280  0.190777   
16 -0.439173  0.260110  0.243242 -0.224537  0.529320  0.385283  0.128300   
17  0.497501 -0.061447 -0.415107  0.369595  0.395909 -0.821639  1.020823   
18 -0.325949  0.237933  0.270114 -0.141150  0.366262  0.347566  0.172926   
19 -0.212725  0.005082  0.323857  0.317478 -0.315615 -0.142746  0.851244   
20  0.497501  0.426432 -0.139675  0.307055  0.647907 -0.413046  0.101524   
21 -0.017155 -0.438444 -1.060022 -0.130726 -0.641731 -0.985077  0.199702   
22  1.650331 -0.682383 -0.253879  1.036690 -0.804789 -0.010739  0.628113   
23  0.363690  0.570578 -0.126240  0.327902  1.255668  0.033264 -0.050204   

        7         8         9     ...      1490      1491      1492      1493  \
0  -1.801425 -1.637387 -2.049345  ...  1.621112  0.881248 -2.783306  2.640365   
1   0.507430  0.268083  0.266070  ...  0.213623 -0.135577  0.228841  0.178718   
2  -1.825351 -0.881017 -0.887575  ...  2.305001 -0.929669 -0.616841  1.697266   
3   0.674911  0.272932  0.469176  ...  0.204799 -0.164629  0.238343  0.173390   
4  -1.155424 -0.754956  0.274194  ... -1.608610 -2.730901  1.863192 -1.712807   
5   0.531356  0.268083  0.274194  ...  0.231272 -0.174313  0.228841  0.205359   
6  -2.303870  4.025689  1.208484  ... -1.515954  0.135577  0.713445 -0.535266   
7   0.543319  0.205052  0.225448  ...  0.222448 -0.174313  0.247845  0.189375   
8   0.650985  0.277780  0.225448  ...  0.213623 -0.125893  0.304857  0.178718   
9   0.531356  0.258386  0.274194  ... -1.388001  2.430696  1.074522 -1.217281   
10  0.555282  0.263234  0.298567  ...  0.218036 -0.125893  0.219339  0.146749   
11 -0.581201 -0.003434 -1.228794  ... -0.584983  1.142718 -1.091943 -1.361143   
12  0.531356  0.219598  0.266070  ...  0.213623 -0.106525  0.219339  0.173390   
13 -1.944981 -0.914957 -3.471090  ... -1.388001 -0.058104 -0.094229 -1.936593   
14  0.519393  0.234143  0.298567  ...  0.213623 -0.242101  0.238343  0.210687   
15  0.567245  0.214749  0.314815  ...  0.218036 -0.145261  0.228841  0.189375   
16  0.639022  0.282629  0.314815  ...  0.213623 -0.174313  0.228841  0.189375   
17  0.208355 -0.963442  1.110993  ... -0.126115 -1.249242  1.017510  0.759496   
18  0.543319  0.253537  0.282318  ...  0.231272 -0.087156  0.257347  0.173390   
19  0.256207 -0.517378  0.737277  ...  1.378441  0.319574 -1.101445  0.663588   
20  0.973986 -0.449499  0.144206  ... -0.589395  2.188595 -2.346212 -0.226228   
21 -0.006978 -0.871320  0.688531  ... -1.639496  0.213049 -0.483812 -1.425082   
22  0.076762  0.020808  0.517922  ...  1.224015 -0.919984  0.903486  0.610305   
23  1.308949 -0.071314 -0.554481  ... -0.081993  0.232417  0.304857  0.034856   

        1494      1495      1496      1497      1498      1499  
0   0.117178 -1.

In [72]:
dt = DecisionTreeClassifier(criterion="gini", random_state=42,
        splitter="best",
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        min_weight_fraction_leaf=0.0,
        max_features=None,
        max_leaf_nodes=None,
        min_impurity_decrease=0.0,
        class_weight=None,
        ccp_alpha=0.0,
        monotonic_cst=None)

Without Preprocessing and Featurization

In [96]:


X_collected_train, X_collected_test, y_collected_train, y_collected_test = train_test_split(X_collected, y_collected, test_size=0.3, random_state=42)

dt.fit(X_collected_train, y_collected_train)

predictions = dt.predict(X_collected_test)

accuracy = accuracy_score(predictions, y_collected_test)
print(f"Accuracy: {accuracy}")

precision = precision_score(predictions, y_collected_test,average="weighted")
print(f"Precision: {precision}")

recall = recall_score(predictions, y_collected_test,average="weighted")
print(f"Recall: {recall}")

mat = confusion_matrix(predictions, y_collected_test)
print(f"Confusion Matrix:\n{mat}")

Accuracy: 0.125
Precision: 0.5
Recall: 0.125
Confusion Matrix:
[[0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 2 1 1]]


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


With only Preprocessing

In [97]:

X_collected_standardized_train, X_collected_standardized_test, y_collected_train, y_collected_test = train_test_split(X_collected, y_collected, test_size=0.3, random_state=42)

dt.fit(X_collected_standardized_train, y_collected_train)

predictions = dt.predict(X_collected_standardized_test)

accuracy = accuracy_score(predictions, y_collected_test)
print(f"Accuracy: {accuracy}")

precision = precision_score(predictions, y_collected_test,average="weighted")
print(f"Precision: {precision}")

recall = recall_score(predictions, y_collected_test,average="weighted")
print(f"Recall: {recall}")

mat = confusion_matrix(predictions, y_collected_test)
print(f"Confusion Matrix:\n{mat}")

Accuracy: 0.125
Precision: 0.5
Recall: 0.125
Confusion Matrix:
[[0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 2 1 1]]


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


With only Featurization

In [95]:
X_collected_tsfel_train, X_collected_tsfel_test, y_collected_tsfel_train, y_collected_tsfel_test = train_test_split(X_collected_tsfel.iloc[1:,:], y_collected_tsfel, test_size=0.3, random_state=42)

dt.fit(X_collected_tsfel_train, y_collected_tsfel_train)

predictions = dt.predict(X_collected_tsfel_test)

accuracy = accuracy_score(predictions, y_collected_tsfel_test)
print(f"Accuracy: {accuracy}")

precision = precision_score(predictions, y_collected_tsfel_test,average="weighted")
print(f"Precision: {precision}")

recall = recall_score(predictions, y_collected_tsfel_test,average="weighted")
print(f"Recall: {recall}")


mat = confusion_matrix(predictions, y_collected_tsfel_test)
print(f"Confusion Matrix:\n{mat}")


Accuracy: 0.7142857142857143
Precision: 0.7857142857142857
Recall: 0.7142857142857143
Confusion Matrix:
[[0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 2 0]
 [0 0 1 0 2]]


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


With Preprocessing and featurization

In [99]:
X_collected_standardized_tsfel_train, X_collected_standardized_tsfel_test, y_collected_tsfel_train, y_collected_tsfel_test = train_test_split(X_collected_standardized_tsfel.iloc[1:,:], y_collected_tsfel, test_size=0.3, random_state=42)

dt.fit(X_collected_standardized_tsfel_train, y_collected_tsfel_train)

predictions = dt.predict(X_collected_standardized_tsfel_test)

accuracy = accuracy_score(predictions, y_collected_tsfel_test)
print(f"Accuracy: {accuracy}")

precision = precision_score(predictions, y_collected_tsfel_test,average="weighted")
print(f"Precision: {precision}")

recall = recall_score(predictions, y_collected_tsfel_test,average="weighted")
print(f"Recall: {recall}")


mat = confusion_matrix(predictions, y_collected_tsfel_test)
print(f"Confusion Matrix:\n{mat}")


Accuracy: 0.7142857142857143
Precision: 0.7857142857142857
Recall: 0.7142857142857143
Confusion Matrix:
[[0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 2 0]
 [0 0 1 0 2]]


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


It can be clearly seen that that after no difference in accuracy/recall/precision occurs after preprocessing the given data(Standardizing it) but after featurization using tsfel the the accuracy/recall/precision of the model increases substantialy so model performs a lot better after featurization.